import random



titles = [
    'chief',
    'king',
    'earl',
    'queen',
    'baron',
    'prince',
    'crown prince',
    'duke',
    'archduke',
    'princess',
    'duchess',
    'despot',
    'count',
    'knight',
    'nobile',
    'elder',
    'gentleman',

    'lecturer',
    'teaching assistant',
    'professor',
    'professor emeritus',

    'acolyte',
    'pope',
    'cleric',
    'chaplain',
    'bishop',
    'deacon',
    'shaman',
    'oracle',
    'monk',
    'preistess',
    'cardinal',
    'friar',
    'nun',
    'scholar',

    'ambassador',
    'prime minister',
    'president',
    'minister',
    'envoy',
    'monarch',
    'counselor',
    'secretary',
    'trade representative',
    # # # # 
    'dental assistant',
    'optometrist',
    'midwife',
    'thespian',
    'barista',
    'barbarian',
    'warlock',
    'cowboy',
    'hairdresser',
    'gardener',
    'florist',
    'poet',
    'hematologist',
    'sales representative',
    'waiter',
    'mercenary',
    'saxophonist',
    'impressionist',
    'surrealist',
    'lifeguard',
    'model',
    'mime',
    'clown',
    'pilot',
    'truck driver',
    'radiologist',
    'urchin',
    'hermit',
    'visionary',
    'prophet',
    'DJ',
    'patient',
    'pickpocket',
    'dietician',
    'mortician',
    'referee',
    'curator',
    'art collector',
    'librarian',
    'mathematician',
    'tutor',
    'sociologist',
    'archivist',
    'therapist',
    'psychiatrist',
    'carpenter',
    'electrician',

    'admiral',
    'commodore',
    'field marshal',
    'general',
    'lieutenant',
    'officer',
    'midshipman',
    'lieutenant',
    'cadet',
    'private',
    'warrant officer',
    'sergeant',
    'corporal',

    'director',
    'groundskeeper',
    'gravedigger',
    'night watchman',
    'security guard',
    'janitor',
    'postal worker',
    'intern',
    'composer',
    'architect',
    'engineer',
    'sculptor',
    'painter',
    'dancer',
    'choreographer',
    'creative director',
    'director',
    'violinist',
    'cellist',
    'bassist',
    'guitarist',
    'drummer',
    'organist',
    'pianist',
    'house cleaner',
    'mechanic',
    'stonemason',
    'street vendor',
    'singer',
    'sailor',
    'referee',
    'plumber',
    'paralegal',
    'painter',
    'metermaid',
    'meat packer',
    'judge',
    'hydrologist',
    'hunter',
    'fisherman',
    'escort',
    'courier',
    'surgeon',
    'gossip',
    'weaver',
    'seamstress',
    'martyr',
    'samaritan',
    'tyrant',
    'fool',
    'dunce',
]

# -------------------

# prefixes for jobs
# title_rankings = [
#     'assistant'
#     'head',
#     'senior',
#     'high',
#     'chief',
#     'grand',
#     'full-time',
#     'associate',
#     'adjunct',
#     'former',
#     'first',
#     'executive',
#     'secondary',
#     'second',
#     'third',
#     'pimeiro'
# ]

# title_prefixes = [
#     'arch'
#     'demi-'
# ]


def get_title():
    
    return random.choice(titles)
